#!/bin/bash

# common for all SUTs
echo "All SUTs"
echo "--------"
echo "Environment = $Environment"
echo "GeographicaScriptsDir = $GeographicaScriptsDir"
echo "DatasetBaseDir = $DatasetBaseDir"
echo "QuerysetBaseDir = $QuerysetBaseDir"
echo "ResultsBaseDir = $ResultsBaseDir"
echo "ResultsDirName = $ResultsDirName"
echo "ActiveSUT = $ActiveSUT"
echo "ExperimentResultDir = $ExperimentResultDir"
echo "ExperimentDesc = $ExperimentDesc"
echo "CompletionReportDaemonIP = $CompletionReportDaemonIP"
echo "CompletionReportDaemonPort = $CompletionReportDaemonPort"
echo "ScalabilityGenScriptName = ${ScalabilityGenScriptName}"
echo "ScalabilityGzipRefDSName = ${ScalabilityGzipRefDSName}"
echo "SystemMemorySizeInGB = ${SystemMemorySizeInGB} GBs"
echo "JVM_Xmx = $JVM_Xmx"
echo ""
# GraphDBSUT only
echo "GraphDB SUT"
echo "-----------"
echo "GraphDBBaseDir = $GraphDBBaseDir"
echo "GraphDBDataDir = $GraphDBDataDir"
echo "EnableGeoSPARQLPlugin = $EnableGeoSPARQLPlugin"
echo "IndexingAlgorithm = $IndexingAlgorithm"
echo "IndexingPrecision = $IndexingPrecision"
echo "Version = ${verGRAPHDB}"
echo ""
# RDF4JSUT only
echo "RDF4J SUT"
echo "---------"
echo "RDF4JRepoBaseDir = $RDF4JRepoBaseDir"
echo "EnableLuceneSail = $EnableLuceneSail"
echo "RDF4JLuceneReposPrefix = ${RDF4JLuceneReposPrefix}"
echo "Version = ${verRDF4J}"
echo ""
# StrabonSUT only
echo "Strabon SUT"
echo "-----------"
echo "StrabonBaseDir = $StrabonBaseDir"
echo "StrabonLoaderBaseDir = $StrabonLoaderBaseDir"
echo ""
# Virtuoso SUT only
echo "Virtuoso SUT"
echo "-----------"
echo "VirtuosoBaseDir = $VirtuosoBaseDir"
echo "VirtuosoDataBaseDir = $VirtuosoDataBaseDir"
echo "VirtuosoTemplateConfigurationFile = $VirtuosoTemplateConfigurationFile"
echo "NumberOfBuffers = ${NumberOfBuffers} 8k-pages"
echo "MaxDirtyBuffers = ${MaxDirtyBuffers} 8k-pages"
echo ""
# StardogSUT only
echo "Stardog SUT"
echo "-----------"
echo "StardogBaseDir = $StardogBaseDir"
echo "STARDOG_HOME = $STARDOG_HOME"
echo "StardogSpatialPrecision = $StardogSpatialPrecision"
echo "STARDOG_EXT = $STARDOG_EXT"
echo "StardogLoadPropertyFile = $StardogLoadPropertyFile"
echo "StardogQueryPropertyFile = $StardogQueryPropertyFile"
echo "Version = ${verSTARDOG}"
echo "STARDOG_SERVER_JAVA_ARGS = ${STARDOG_SERVER_JAVA_ARGS}"
echo ""
# JenaGeoSPARQLSUT only
echo "JenaGeoSPARQL SUT"
echo "-----------------"
echo "JenaBaseDir = $JenaBaseDir"
echo "JenaGeoSPARQLRepoBaseDir = $JenaGeoSPARQLRepoBaseDir"
echo ""